name = "ltm-world-worker"
main = "worker.js"  # Path relative to root
compatibility_date = "2025-04-10"

[[d1_databases]]
binding = "DB"
database_name = "ltm-world-db"
database_id = "2ff0565d-85d4-4247-9060-1bad62918796"